# Generated by Django 3.1.7 on 2021-02-25 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LocationEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimoine.equipment')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimoine.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='equipments',
            field=models.ManyToManyField(blank=True, through='patrimoine.LocationEquipment', to='patrimoine.Equipment'),
        ),
        migrations.CreateModel(
            name='BuildingLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimoine.building')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimoine.location')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='locations',
            field=models.ManyToManyField(blank=True, through='patrimoine.BuildingLocation', to='patrimoine.Location'),
        ),
    ]
